### ISSUE TITLE
Список зависимостей не полный

### ISSUE THREAD

**Issue by g0dzZz-coder** [fffogil/Comfy-Google-Sheets#1]
Помимо `Google.Apis.Sheets.v4` пакет для работы требует еще следующие плагины:

- [Google.Apis](https://www.nuget.org/packages/Google.Apis)
- [Google.Apis.Core](https://www.nuget.org/packages/Google.Apis.Core)
- [Google.Apis.Auth](https://www.nuget.org/packages/Google.Apis.Auth)

Возможно стоит указать это в Readme?

**Comment by ligofff** [comment]
Привет! Спасибо что подметил.
Пока  не думаю что нужно добавлять, т.к. это всё входит в зависимости `Google.Apis.Sheets.v4`

![image](https://github.com/ligofff/Comfy-Google-Sheets/assets/44195161/7669f720-b505-485a-b628-f9f6fbb9e7b8)

Но возможно стоит. Подскажи, у тебя были проблемы с установкой связанные с этим?

**Comment by g0dzZz-coder** [comment]
С [Google.Apis.Auth](https://www.nuget.org/packages/Google.Apis.Auth) проблем не было, т.к. явно указан `namespace` в твоих скриптах. С остальными оказалось не совсем очевидно
![image](https://github.com/ligofff/Comfy-Google-Sheets/assets/47529116/481d9cc2-b536-46bb-a1c1-bbde3b4170d9)

Я сам виноват, потому что не обратил внимание на зависимости в `NuGet` (со скрина, что ты прикрепил).
Посчитал важным отменить это как проблему, потому указание только 1-й зависимости немного вводит в замешательство. Чуть было не отказался от этого пакета из-за таких головоломок в ходе интеграции)

Btw, спасибо за проделанную работу!

**Comment by ligofff** [comment]
b850f26084b578fd45593ee0be2f2450caaf9f70 - добавил небольшое напоминание об установке зависимостей.
Спасибо!
